#+AUTHOR: FCIM FAF 203 Covtun Serghei

* INTRO TO CRYPTOGRAPHY. CLASSICAL CIPHERS. CAESAR CIPHER.

** THEORY

*** What is Cryptography?

The study of mathematical techniques for securing digital information, systems, and distributed computations against adversarial attacks.

** OBJECTIVES

- Get familiar with the basics of cryptography and classical ciphers.
- Implement 4 types od the classical ciphers:
  - Caesar cipher with one key used for substitution (as explained above),
  - Caesar cipher with one key used for substitution, and a permutation of the alphabet,
  - Vigenere cipher,
  - Atbash cipher.
- Structure the project in methods/classes/packages as neeeded.

** IMPLEMENTATION

*** CAESAR CIPHER

The Caesar Cipher technique is one of the earliest and simplest methods of encryption technique. It’s simply a type of substitution cipher, i.e., each letter of a given text is replaced by a letter with a fixed number of positions down the alphabet. For example with a shift of 1, A would be replaced by B, B would become C, and so on. The method is apparently named after Julius Caesar, who apparently used it to communicate with his officials.

Algorithm for Caesar Cipher:

1. Traverse the given text one character at a time .
2. For each character, transform the given character as per the rule, depending on whether we’re encrypting or decrypting the text.
3. Return the new string generated.

Example:

#+begin_example
Text : attack
Shift: 3
Cipher: dwwdfn
#+end_example

*** VIGENERE CIPHER

Vigenere Cipher is a method of encrypting alphabetic text. It uses a simple form of polyalphabetic substitution. A polyalphabetic cipher is any cipher based on substitution, using multiple substitution alphabets. The encryption of the original text is done using the Vigenère square or Vigenère table.

- The table consists of the alphabets written out 26 times in different rows, each alphabet shifted cyclically to the left compared to the previous alphabet, corresponding to the 26 possible Caesar Ciphers.
- At different points in the encryption process, the cipher uses a different alphabet from one of the rows.
- The alphabet used at each point depends on a repeating keyword.

Example:

#+begin_example
Plaintext :   ATTACK
Keyword   :   HALO

Ciphertext :  HTEOJK
#+end_example

The first letter of the plaintext, G is paired with A, the first letter of the key. So use row G and column A of the Vigenère square, namely G. Similarly, for the second letter of the plaintext, the second letter of the key is used, the letter at row E, and column Y is C. The rest of the plaintext is enciphered in a similar fashion.


*** Atbash CIPHER

=The Atbash Cipher=
Atbash cipher is a substitution cipher with just one specific key where all the letters are reversed that is A to Z and Z to A. 
It was originally used to encode the Hebrew alphabets but it can be modified to encode any alphabet. 
For example:

#+begin_example
PlainText  : "ATTACK"
Ciphertext :  ZGGZXP
#+end_example
